[package]
name = "wallcreeper"
version = "0.1.0"
edition = "2024"

[lints]
rust.unsafe_code = "forbid"
rust.unused_results = "deny"
clippy.allow_attributes = "deny"
clippy.allow_attributes_without_reason = "deny"
clippy.arithmetic_side_effects = "deny"
clippy.let_underscore_untyped = "deny"
clippy.todo = "warn"
clippy.nursery = { level = "warn", priority = -1 }
clippy.pedantic = { level = "warn", priority = -1 }
